repos:
  - repo: local
    hooks:
      - id: clang-format-staged
        name: clang-format staged C/C++ files
        entry: clang-format
        args: ["-i"]
        language: system
        pass_filenames: true
        types_or: [c, c++]
      - id: quick-tests
        name: run quick tests
        entry: just quick-check
        language: system
        pass_filenames: false
